about/camara.md
about/glossary.md
about/initiative.md
about/privacy.md
callflows/apiintegration.md
callflows/authorization/authorization.md
catalog/available.md
catalog/roadmap.md
gettingstarted/programs.md
gettingstarted/sandbox/sandbox.md

They are cool, but brand masters prefer to keep it serious :(

Remove emojis

---

catalog/devicelocation/devicelocation_openapi.yaml

According to https://github.com/camaraproject/DeviceLocation/blob/78a819477d3b7484298e560481dce000751e4550/code/API_definitions/location.yaml#L20

Fix Device Location purpose

---

catalog/numberverification/samplecode_numberverification.md
catalog/simswap/samplecode_simswap.md

Callouts warning that the code is sample code

Lufu ogw/callouts

---

catalog/available.md
catalog/roadmap.md

Sencillamente he puesto las apis que ya están disponibles en el sandbox en el apartado available

updated roadmap: device status, device location y QoD in available

---

gettingstarted/sandbox/sandbox.md

Actualizar porque ya están disponibles en Movistar:
- QoD
- Number Verification
- Device Location

Update APIs available on the Sandbox

---

catalog/devicelocation/devicelocation.md
catalog/devicestatus/devicestatus.md
catalog/numberverification/numberverification.md

Lufu ogw/media resources

---

catalog/numberverification/samplecode_numberverification.md
catalog/simswap/samplecode_simswap.md

No se veían bien los callouts. Los he dejado de forma más simple.

callouts fixed

---

gettingstarted/sandbox/sandbox.md

Adding:
- KYC on mock
- Device Status on Movistar

Update Sandbox catalog

---

catalog/knowyourcustomer/knowyourcustomer.md

Some changes which Clara as API's PM things must be done to avoid product misunderstanding or overpromising, and which has been required for marketing website
PD: We must review our content strategy on contents that are published in the marketing website as well

Feedback from Clara API's PM

---

catalog/knowyourcustomer/kyc_match_openapi.yaml

Experimento de cómo funcionan en readme.com las versiones de APIs
- Por lo que he visto, cada versión de un endpoint se debe especificar en el openapi como operaciónes/paths distintos
- Vamos a probar subiendo a producción a ver cómo queda, y si no queda bien reaccionamos rápido ...porque con el plan de readme.com que tenemos no tenemos incluido el entorno de stagging para probar los cambios antes de publicarlos 😞

Add KYC 0.2 version

---

catalog/devicelocation/devicelocation_openapi.yaml
catalog/devicestatus/devicestatus_openapi.yaml
catalog/knowyourcustomer/kyc_match_openapi.yaml
catalog/numberverification/numberverification_openapi.yaml
catalog/qod/qod_openapi.yaml
catalog/simswap/simswap_openapi.yaml

Nos ha pedido algún PM que indiquemos claramente la versión en los API reference, porque tienen clientes que la están usando y no están seguros de si están viendo la misma versión que quieren consumir

Include version in operation summary

---

gettingstarted/sandbox/sandbox.md

Embed video from youtube. If it feels good, we'll add the Short4Devs of SIM Swap, Device Location and Number Verification

Video sandbox added to Sandbox page

---

.github/workflows/rdme-guides-openapi.yml
.vscode/settings.json
catalog/deviceswap/deviceswap.md
catalog/deviceswap/deviceswap_openapi.yaml
catalog/simswap/simswap_openapi.yaml

Adding Device Swap API supporting material:
- A guide
- The API reference

Device Swap

---

catalog/devicelocation/devicelocation.md
catalog/devicelocation/samplecode_devicelocation.md

Important and urgent!
Changes requested by the API's product manager Javier Carro

Fixes requested by APIs PM

---

callflows/authorization/authorization_openapi.yaml
gettingstarted/sandbox/usethesandbox.md

According to https://github.com/Telefonica/opengateway-developers-website/pull/52#issuecomment-2511410248

Revert PR #52

---

callflows/authorization/backend.md

https://dash.readme.com/project/open-gateway-developers/v1.0/suggested/update/674e357cfab086004b300e19

Suggested edit by @palmerabollo on readme.com

---

about/initiative.md

We need to change the order of the CTA. It should be visible in the initiative page after the first paragraph

Change order CTA

---

gettingstarted/sandbox/sandbox.md

It was duplicated:
Please note that the usage of credentials granted from our Sandbox might be subject to some limitations in order to let you test without the obligations of a commercial contract. The terms and conditions of our developer or partner programs will apply.

Duplicated Paragraph

---

catalog/devicelocation/samplecode_devicelocation.md
catalog/numberverification/samplecode_numberverification.md
catalog/qod/samplecode_qod.md
catalog/simswap/samplecode_simswap.md

Add sandbox code
Fix format in simsap code tabs.

Add sandbox sample code

---

about/initiative.md

Adding references about the GSMA status to give info about the status of the project in the different countries. It's a link to this website: https://open-gateway.gsma.com

Info about the GSMA status

---

about/initiative.md
gettingstarted/sandbox/usethesandbox.md

Videos with code
